### ISSUE TITLE
S3 test could fail: check download file

### ISSUE THREAD

**Issue by haiodo** [hardcoreeng/platform#489]
S3 test failed
```
--[ FAILURE: @anticrm/s3 ]----------------------------------[ 33.47 seconds ]--
5751
5752  ● s3 › check download file
5753
5754    expect(received).toEqual(expected) // deep equality
5755
5756    Expected: {"data": [116, 101, 115, 116, 84, 101, 120, 116], "type": "Buffer"}
5757    Received: undefined
5758
5759       99 |       // eslint-disable-next-line
5760      100 |       void client.getFile(fileName).then((res) => {
5761    > 101 |         expect(res?.body).toEqual(file)
5762          |                           ^
5763      102 |         fs.unlinkSync(`./${fileName}`)
5764      103 |         done()
5765      104 |       })
5766
5767      at src/__tests__/s3.test.ts:101:27
5768
5769
[jest] Error: 1 Jest test failed
```

**Comment by haiodo** [comment]
One more failure:

```
--[ FAILURE: @anticrm/s3 ]----------------------------------[ 29.90 seconds ]--
5761
5762  ● s3 › check download file
5763
5764    expect(received).toEqual(expected) // deep equality
5765
5766    Expected: {"data": [116, 101, 115, 116, 84, 101, 120, 116], "type": "Buffer"}
5767    Received: undefined
5768
5769      102 |       // eslint-disable-next-line
5770      103 |       void client.getFile(fileName).then((res) => {
5771    > 104 |         expect(res?.body).toEqual(file)
5772          |                           ^
5773      105 |         fs.unlinkSync(`./${fileName}`)
5774      106 |         done()
5775      107 |       })
5776
5777      at src/__tests__/s3.test.ts:104:27
5778
5779 [jest] Error: 1 Jest test failed
5780 Encountered 1 errors:
5781 [jest] 1 Jest test failed
```
